SCOOTWORKS_ITEMS_JUNK_FILTERS_APPAREL = "apparel"
SCOOTWORKS_ITEMS_JUNK_FILTERS_WEAPON = "weapon"
SCOOTWORKS_ITEMS_JUNK_FILTERS_JEWELRY = "jewelry"
SCOOTWORKS_ITEMS_JUNK_FILTERS_MISC = "misc"

SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_ALL = "rest"
SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_INTRICATE = "intricate"
SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_ORNATE = "ornate"

SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_HEAD_SHOULDER = "headShoulder"
SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_TRASH = "trash"
SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_TROPHY = "trophy"
SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_RAREFISH = "rarefish"
SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_TREASURE = "treasure"
SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_GLYPHE = "glyphe"
SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_POTION = "potion"
SCOOTWORKS_ITEMS_JUNK_FILTERS_OPTION_POISON = "poison"

SCOOTWORKS_ITEMS_SETTING_LOOT_OPTION_PLAYER = 1
SCOOTWORKS_ITEMS_SETTING_LOOT_OPTION_GROUP = 2
SCOOTWORKS_ITEMS_SETTING_LOOT_OPTION_ALL = 3